name: Deployment
on:
  push:
    branches:
      - main
jobs:

  test:
    name: Run Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test code
        run: mvn compile test

  upload-image-to-registry:
    name: Build image and push to GCP
    needs: test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: java-crud-gh-actions
      PROJECT_ID: gh-actions-403902
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-west2-docker.pkg.dev --quiet
          echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Push Docker Image to Container Registry (GCR)
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest